### ISSUE TITLE
Single line not single line

### ISSUE THREAD

**Issue by lawrence-laz** [david-vanderson/dvui#106]
Pressing and holding enter on a single line widget creates multiple lines:
<img width="482" alt="image" src="https://github.com/user-attachments/assets/eb1697d3-ae22-45c4-9572-26ffbc2b31a8">

**Comment by david-vanderson** [comment]
Thanks very much for the report!  I've pushed a fix.  Does it work for you now?

**Comment by lawrence-laz** [comment]
Is it deployed to the online demo already? Because I can still reproduce it there

**Comment by david-vanderson** [comment]
Sorry - I just deployed to the online demo.  Sometimes I have trouble getting my browser to reload it, so check that, but I see it fixed now.

**Comment by lawrence-laz** [comment]
Looks good!

**Comment by david-vanderson** [comment]
Thank you!
