### ISSUE TITLE
One Last Menu Behavior Issue

### ISSUE THREAD

**Issue by br07h3rj** [david-vanderson/dvui#521]
Could we suppress the highlights (hover color and focus_as_border outline) that remains on regular menu items when the mouse leaves a floatingMenu? Common practice seems to be that submenus remain open and that the menu item that opened the submenu remains highlighted as long as the submenu is open (which is already working fine), but all other highlights disappear unless the mouse is present. Unless I've missed something, this change would bring us into full alignment with standard system menu behavior. (I still haven't completed all feature-testing, but we're getting a lot closer to being done with the menus.)

**Comment by david-vanderson** [comment]
I see what you mean, that is a good idea.  I'm traveling currently but will look into this when back.

Thanks very much for the thorough testing and focus on the details!

**Comment by david-vanderson** [comment]
I've pushed maybe a fix - it stops the menu item from being colored in the highlight colors, but it is still colored with "hover" stuff.  That kind of makes sense because if you press enter that item will be activated, but unsure.  Thoughts?

**Comment by david-vanderson** [comment]
@br07h3rj Is this good?

**Comment by br07h3rj** [comment]
Thanks for getting back to this. (And I just realized I missed it! Sorry about that!) It's still not quite there, but we're getting really close. Most of what we've got is right on. I over-looked a couple of details about keyboard navigation and I think I now understand better some things you were saying before. (tl;dr checklist below)

Typically, when the mouse opens a menu, no highlighting is present unless there's a hover or a click. When the keyboard opens a menu, the first item is automatically highlighted. This also applies to submenus. Is there a reasonable way to make that happen?

Typically, if the mouse cursor leaves the menu so nothing is highlighted, the keyboard navigation will start from the last hovered item, but there is no highlighting to show which item that was. It'll become apparent when the user starts navigating with the keyboard. (We don't want highlighting to track for keyboard navigation until keyboard navigation starts.)

Typically, Right will open submenus and Left will close them, but, if the selected item is not a submenu-opener, it will navigate between the parent menus left and right without moving focus to the parent menus (and that will wrap from left to right and back). Typical keyboard navigation never moves focus to the menubar item (e.g. File, Edit) once a menu has been opened. (I remember some old systems that worked differently, but this is what I'm seeing now.)

Lastly (and least importantly), the menus I'm seeing will automatically open a submenu if the item that opens it is selected (either keyboard or mouse) for about 500ms.

Checklist (same as above):
- When menus are operated by mouse, no highlighting is present unless cursor is present.
	Submenus do the same.
- When menus are operated by keyboard, first entry is automatically highlighted.
	Submenus do the same.
- When not highlighting a submenu-opening item in a first-level menu, Left and Right will navigate menubar items.
	All submenus just open and close with Left and Right.
- Open submenu when submenu-opening item is highlighted by any means for 500ms. (Optional)

That seems like a lot of work to put on you. If I wasn't so early in my Zig learning, I would try to help. I'll contribute something more significant soon.

**Comment by david-vanderson** [comment]
Good - we are getting into the really small stuff now:

> Checklist (same as above):
> 
>     * When menus are operated by mouse, no highlighting is present unless cursor is present.
>       Submenus do the same.
I think we could make this happen, but it's low priority.  I don't understand why typically they remove all highlighting, even the subtle "hover" kind, because the menu is still the thing with keyboard focus.  So I'm tempted to say that dvui is doing a better job here.  Also at least on macs, the submenus retain their "hover" highlight even when the mouse is outside the whole menu (maybe I misunderstood this part).
> 
>     * When menus are operated by keyboard, first entry is automatically highlighted.
>       Submenus do the same.
This doesn't seem to be the case on macs, at least the top level submenus.  But yes we should probably do this.
> 
>     * When not highlighting a submenu-opening item in a first-level menu, Left and Right will navigate menubar items.
>       All submenus just open and close with Left and Right.
Good point.  This will need more thought, because dvui menus are more flexible with less overall structure.  Think of a top-level vertical menu, or a horizontal menu inside a submenu.  But those are likely to be niche cases.
> 
>     * Open submenu when submenu-opening item is highlighted by any means for 500ms. (Optional)
This is interesting.  That small of a delay seems unneeded, so we should try always opening the submenu if it's highlighted.  We already do that for mouse.

**Comment by br07h3rj** [comment]
I've never owned a Mac and haven't used one in probably more than 20 years. I'll defer to your experience on all things Mac-related.

I've thought about it more and maybe the delay on auto-opening the submenu is not as optional as I thought. It's paired with auto-highlighting the first entry for keyboards. If we auto-highlight the first entry, that means auto-opening the submenu will suck the focus into the submenu whether the user wants to go there or not. So, we could

1) delay the auto-opening and auto-highlight the first entry (which takes the user into the submenu in half a second) or

2) auto-open immediately and make the user press Right to get into the submenu.

The first solution is the one I'm used to and I think it would feel smoother, but the second one is definitely easier.

>  I don't understand why typically they remove all highlighting, even the subtle "hover" kind, because the menu is still the thing with keyboard focus.

I'm guessing here, but I think it's because almost all users will either exclusively use the mouse for menus or the keyboard, without much cross-over. The mouse users might think it looks cleaner without the residual hover and the keyboard users won't even notice because they're not using mouse hover at all. I didn't know that Mac's preserve the hover. I would guess that decision was made for the same reason you're thinking. Could we compromise by making it into an init option? Ideally, I would like to be able to turn it off.

> This will need more thought, because dvui menus are more flexible with less overall structure. Think of a top-level vertical menu, or a horizontal menu inside a submenu. But those are likely to be niche cases.

I really like that you want to preserve flexibility for edge cases. I'm into it, even though this particular case is kinda wonky. It sounds like we would need to write the menus to have horizontal and vertical modes for keyboard controls if we want it to be that kind of flexible.
