### ISSUE TITLE
WebGL demo invalid utf8

### ISSUE THREAD

**Issue by wilsonk** [david-vanderson/dvui#72]
I tried the demo with webgl2 and it looks/works well except the multiline TextEntry widget throws error.invalidUtf8 when I try to ctrl-x some text and repaste with ctrl-v. It seemed to work with two characters the first time I pasted, but failed the second time.

Tested again and it happened on the first go this time. Perhaps the demo hasn't been updated with the copyForwards fixes from yesterday? Or maybe something else :)

**Comment by david-vanderson** [comment]
You are right - the webgl backend copy/paste is currently broken.  In fact, the implementation currently doesn't actually try to do anything - copy does nothing, and paste should paste the text "clipboard".  I haven't looked into why that's throwing errors yet.

Can you tell me what platform (phone vs computer, which browser) you are on?

**Comment by wilsonk** [comment]
None tested on phone. All PC.

Linux-Firefox -- invalidUtf8
Linux-Brave -- same

Win-Firefox -- same
Win-Edge -- same

MacOS-Monterey-Brave --  same
MacOS-Monterey-Safari --  cut and then everything gets erased from my paste char to the bottom of my input and replaced with a 'C'

**Comment by david-vanderson** [comment]
Thanks so much for the wide testing!  Give me some time to look into it.

**Comment by david-vanderson** [comment]
I've committed a first try.  Can you retest and tell me how it looks now?

**Comment by wilsonk** [comment]
Looks good on all the platforms and browsers except MacOs.  On Mac (both Safari and Brave), I can cut but the paste just does nothing...then strangely if I try to copy just after a cut-and-failed-paste, the whole browser window flashes and nothing happens! Strange. That is on both browsers.

**Comment by david-vanderson** [comment]
Thanks!  That's progress.  I'll look into the Mac thing.  Is there anything weird in the javascript dev console in either browser on Mac?

**Comment by wilsonk** [comment]
On Mac with Brave I get this when I cut, paste and then try to copy (and get the screen flash).

```
WebBackend.js?cache-buster=1716391637574504311:310 Uncaught RangeError: Start offset -1 is outside the bounds of the buffer
    at new Uint8Array (<anonymous>)
    at wasm_clipboardTextSet (WebBackend.js?cache-buster=1716391637574504311:310:42)
    at Backend.init__anon_7591.gen.clipboardTextSetImpl (00dcb72a:0x44c2)
    at widgets.TextLayoutWidget.addTextEx (00dcb72a:0x16474)
    at widgets.TextEntryWidget.draw (00dcb72a:0x3d746)
    at dvui.textEntry (00dcb72a:0x1c29b)
    at Examples.textEntryWidgets (00dcb72a:0x2f557)
    at Examples.demo (00dcb72a:0x1883a)
    at web-test.update (00dcb72a:0x9e4b)
    at app_update (00dcb72a:0x6935)
```

**Comment by david-vanderson** [comment]
Ah thank you!  Looks like I need to check for trying to copy a zero-length string.  I've done that, does that make it better?

**Comment by wilsonk** [comment]
The screen flicker problem is indeed fixed, and cutting works, but the pasting doesn't do anything on Mac for either browser. Still seems to work fine on the other browsers.

**Comment by david-vanderson** [comment]
Good.  I'm looking into why pasting isn't working on Mac.  Thanks!

**Comment by david-vanderson** [comment]
I've pushed a change to hopefully help on Mac.  Can you try on Mac again?

**Comment by wilsonk** [comment]
Nope, still not working on Mac. With Brave I get this error on cut:
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
```

**Comment by david-vanderson** [comment]
Shoot.  Also that error message should fire on page load, and is only related to the github pages (nothing specific to dvui).  Are you getting that error only after doing a cut?

Can you try it in anonymous (or incognito mode)?  Sometimes I've seen problems where the browser doesn't refetch the files.  Otherwise I'm not sure how to troubleshoot further.  What version of macos are you on?

**Comment by wilsonk** [comment]
MacOS Monterey on M1. Yeah, this time that error appeared on page load, not sure why it waited for a key press last time...this is on Brave.

Now the cut works, but no paste. Then if I copy, that seems to cut the highlighted text also?? Weird. Paste doesn't work at all. No errors are displayed at all during cut, copy or paste.

If you can think of something else for me to try, I can, but I will be offline for a few hours.

**Comment by david-vanderson** [comment]
Unfortunately I can't think of anything else right now.  It's working for me on my old macbook in Firefox, Safari, and Chrome.

I'm glad things are better than they were initially, and unsure how much further to push on this for now.  Do you have a usecase the requires this to work on the web?

**Comment by wilsonk** [comment]
Oh, no I don't have a usecase for this...just ran into the error while testing and thought I would let you know. I am not sure where to go with this either, so perhaps we can wait until someone else needs this and chimes?  :)

**Comment by david-vanderson** [comment]
Sounds like a good plan.  I really appreciate you reporting this and all the testing.  Thanks!
